test_mat:
	cx --debug-profile\
		../src/mat/math.cx\
		../src/mat/v1f.cx\
		../src/mat/v1d.cx\
		../src/mat/v2f.cx\
		../src/mat/v3f.cx\
		../src/mat/v4f.cx\
		../src/mat/q4f.cx\
		../src/mat/m44f.cx\
		../src/fps/profiler.cx\
		test_mat.cx 

